In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import jaccard_similarity_score
from sklearn.metrics import f1_score

In [0]:
dataset = pd.read_csv("loan.csv")

In [3]:
dataset.head()

    Loan_ID Gender Married  ... Credit_History Property_Area Loan_Status
0  LP001002   Male      No  ...            1.0         Urban           Y
1  LP001003   Male     Yes  ...            1.0         Rural           N
2  LP001005   Male     Yes  ...            1.0         Urban           Y
3  LP001006   Male     Yes  ...            1.0         Urban           Y
4  LP001008   Male      No  ...            1.0         Urban           Y

[5 rows x 13 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [5]:
dataset.describe()

       ApplicantIncome  CoapplicantIncome  ...  Loan_Amount_Term  Credit_History
count       614.000000         614.000000  ...         600.00000      564.000000
mean       5403.459283        1621.245798  ...         342.00000        0.842199
std        6109.041673        2926.248369  ...          65.12041        0.364878
min         150.000000           0.000000  ...          12.00000        0.000000
25%        2877.500000           0.000000  ...         360.00000        1.000000
50%        3812.500000        1188.500000  ...         360.00000        1.000000
75%        5795.000000        2297.250000  ...         360.00000        1.000000
max       81000.000000       41667.000000  ...         480.00000        1.000000

[8 rows x 5 columns]

In [6]:
dataset.index

RangeIndex(start=0, stop=614, step=1)

In [7]:
dataset.dtypes[dataset.dtypes == 'object']

Loan_ID          object
Gender           object
Married          object
Dependents       object
Education        object
Self_Employed    object
Property_Area    object
Loan_Status      object
dtype: object

In [0]:
dataset["Loan_Status"] = dataset["Loan_Status"].replace(["N" , "Y"],[0,1])

In [0]:
dataset["Gender"] = dataset["Gender"].replace(["Male" , "Female"],[0,1])

In [0]:
dataset["Married"] = dataset["Married"].replace(["No" , "Yes"],[0,1])

In [0]:
dataset["Education"] = dataset["Education"].replace(["Not Graduate" , "Graduate"],[0,1])

In [0]:
dataset["Self_Employed"] = dataset["Self_Employed"].replace(["No" , "Yes"],[0,1])

In [0]:
dataset = dataset.drop(["Loan_ID"], axis = 1)

In [0]:
dataset = pd.get_dummies(dataset)

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   601 non-null    float64
 1   Married                  611 non-null    float64
 2   Education                614 non-null    int64
 3   Self_Employed            582 non-null    float64
 4   ApplicantIncome          614 non-null    int64
 5   CoapplicantIncome        614 non-null    float64
 6   LoanAmount               592 non-null    float64
 7   Loan_Amount_Term         600 non-null    float64
 8   Credit_History           564 non-null    float64
 9   Loan_Status              614 non-null    int64
 10  Dependents_0             614 non-null    uint8
 11  Dependents_1             614 non-null    uint8
 12  Dependents_2             614 non-null    uint8
 13  Dependents_3+            614 non-null    uint8
 14  Property_Area_Rural      614 non-null    uint8
 15  Property_Area_Semiurban  614 non-null    uint8
 16  Property_Area_Urban      614 non-null    uint8
dtypes: float64(7), int64(3), uint8(7)
memory usage: 52.3 KB

In [16]:
dataset["Gender"][dataset["Gender"].isna()] = dataset["Gender"].mean()
dataset["Married"][dataset["Married"].isna()] = dataset["Married"].mean()
dataset["Self_Employed"][dataset["Self_Employed"].isna()] = dataset["Self_Employed"].mean()
dataset["LoanAmount"][dataset["LoanAmount"].isna()] = dataset["LoanAmount"].mean()
dataset["Loan_Amount_Term"][dataset["Loan_Amount_Term"].isna()] = dataset["Loan_Amount_Term"].mean()
dataset["Credit_History"][dataset["Credit_History"].isna()] = dataset["Credit_History"].mean()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [17]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   614 non-null    float64
 1   Married                  614 non-null    float64
 2   Education                614 non-null    int64
 3   Self_Employed            614 non-null    float64
 4   ApplicantIncome          614 non-null    int64
 5   CoapplicantIncome        614 non-null    float64
 6   LoanAmount               614 non-null    float64
 7   Loan_Amount_Term         614 non-null    float64
 8   Credit_History           614 non-null    float64
 9   Loan_Status              614 non-null    int64
 10  Dependents_0             614 non-null    uint8
 11  Dependents_1             614 non-null    uint8
 12  Dependents_2             614 non-null    uint8
 13  Dependents_3+            614 non-null    uint8
 14  Property_Area_Rural      614 non-null    uint8
 15  Property_Area_Semiurban  614 non-null    uint8
 16  Property_Area_Urban      614 non-null    uint8
dtypes: float64(7), int64(3), uint8(7)
memory usage: 52.3 KB

In [18]:
tm = dataset.groupby('Loan_Status').mean()
v1 = tm.iloc[0,:]
v2 = tm.iloc[1,:]
abs((v2-v1)/(v1+v2))

Gender                     0.043037
Married                    0.072087
Education                  0.049855
Self_Employed              0.005809
ApplicantIncome            0.005726
CoapplicantIncome          0.110365
LoanAmount                 0.022337
Loan_Amount_Term           0.004248
Credit_History             0.265924
Dependents_0               0.005966
Dependents_1               0.090439
Dependents_2               0.160767
Dependents_3+              0.090439
Property_Area_Rural        0.159202
Property_Area_Semiurban    0.202603
Property_Area_Urban        0.065540
dtype: float64

In [0]:
dataset = dataset.drop(["Self_Employed","Loan_Amount_Term"], axis = 1)

In [0]:
Y = dataset["Loan_Status"]
dataset.drop("Loan_Status", axis="columns", inplace=True)
X = dataset

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [27]:
model = RandomForestClassifier()
model.fit(X_train, y_train)
print("Accuracy of Model Using RandomForestClassifier",model.score(X_test, y_test)*100)
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
print("Loan_Status",sum(y_pred == 0))
cm = confusion_matrix(y_test,y_pred)

# jaccard
RNF_Jaccard = jaccard_similarity_score(y_test, y_pred)
print("RandomForestClassifier- jaccard accuracy = " , RNF_Jaccard)

# f1_score
RNF_f1_score = f1_score(y_test, y_pred, average='weighted') 
print("RandomForestClassifier - f1 score accuracy = " , RNF_f1_score)

Accuracy of Model Using RandomForestClassifier 79.87012987012987
Loan_Status 26
RandomForestClassifier- jaccard accuracy =  0.7987012987012987
RandomForestClassifier - f1 score accuracy =  0.7810627914320839

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

In [28]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)
print("Accuracy of Model Using LogisticRegression",classifier.score(X_test, y_test)*100)
from sklearn.metrics import confusion_matrix
y_pred = classifier.predict(X_test)
print("Loan Status",sum(y_pred == 0))
cm = confusion_matrix(y_test,y_pred)

# jaccard
Log_Jaccard = jaccard_similarity_score(y_test, y_pred)
print("LogisticRegression- jaccard accuracy = " , Log_Jaccard)

# f1_score
Log_f1_score = f1_score(y_test, y_pred, average='weighted') 
print("LogisticRegression - f1 score accuracy = " , Log_f1_score)

Accuracy of Model Using LogisticRegression 84.4155844155844
Loan Status 23
LogisticRegression- jaccard accuracy =  0.8441558441558441
LogisticRegression - f1 score accuracy =  0.8269829344209509

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

In [33]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
print("Accuracy of Model Using KNN",classifier.score(X_test, y_test)*100)
from sklearn.metrics import confusion_matrix

y_pred = classifier.predict(X_test)
print("Loan Status",sum(y_pred == 0))
cm = confusion_matrix(y_test,y_pred)

# jaccard
KNN_Jaccard = jaccard_similarity_score(y_test, y_pred)
print("KNN- jaccard accuracy = " , KNN_Jaccard)

# f1_score
KNN_f1_score = f1_score(y_test, y_pred, average='weighted') 
print("KNN - f1 score accuracy = " , KNN_f1_score)

Accuracy of Model Using KNN 59.09090909090909
Loan Status 34
KNN- jaccard accuracy =  0.5909090909090909
KNN - f1 score accuracy =  0.5749704840613932

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)

In [30]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
print("Accuracy of Model Using DecisionTreeClassifier",classifier.score(X_test, y_test)*100)
from sklearn.metrics import confusion_matrix

y_pred = classifier.predict(X_test)
print("Loan Status",sum(y_pred == 0))
cm = confusion_matrix(y_test,y_pred)

# jaccard
DTC_Jaccard = jaccard_similarity_score(y_test, y_pred)
print("DecisionTreeClassifier- jaccard accuracy = " , DTC_Jaccard)

# f1_score
DTC_f1_score = f1_score(y_test, y_pred, average='weighted') 
print("DecisionTreeClassifier - f1 score accuracy = " , DTC_f1_score)

Accuracy of Model Using DecisionTreeClassifier 72.07792207792207
Loan Status 48
DecisionTreeClassifier- jaccard accuracy =  0.7207792207792207
DecisionTreeClassifier - f1 score accuracy =  0.7252332920535686

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)